export const CreatorsFakeDB = [
  {
    name: "Olivia Carter",
    totalRecipes: 24,
    totalVideos: 18,
    followers: 12500,
    following: 210,
    id: 52893,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Olivia%20Carter",
  },
  {
    name: "Ethan Wright",
    totalRecipes: 40,
    totalVideos: 32,
    followers: 18700,
    following: 310,
    id: 52915,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Ethan%20Wright",
  },
  {
    name: "Sophia Green",
    totalRecipes: 18,
    totalVideos: 12,
    followers: 9800,
    following: 150,
    id: 52795,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Sophia%20Green",
  },
  {
    name: "Liam Roberts",
    totalRecipes: 33,
    totalVideos: 25,
    followers: 14200,
    following: 280,
    id: 52947,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Liam%20Roberts",
  },
  {
    name: "Ava Mitchell",
    totalRecipes: 29,
    totalVideos: 20,
    followers: 16000,
    following: 300,
    id: 52821,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Ava%20Mitchell",
  },
  {
    name: "James Parker",
    totalRecipes: 22,
    totalVideos: 16,
    followers: 8900,
    following: 200,
    id: 52984,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=James%20Parker",
  },
  {
    name: "Mia Bennett",
    totalRecipes: 37,
    totalVideos: 29,
    followers: 17400,
    following: 340,
    id: 52902,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Mia%20Bennett",
  },
  {
    name: "Noah Hughes",
    totalRecipes: 15,
    totalVideos: 10,
    followers: 7600,
    following: 120,
    id: 52836,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Noah%20Hughes",
  },
  {
    name: "Isabella Ward",
    totalRecipes: 28,
    totalVideos: 21,
    followers: 15400,
    following: 260,
    id: 52963,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Isabella%20Ward",
  },
  {
    name: "William Morris",
    totalRecipes: 31,
    totalVideos: 23,
    followers: 16900,
    following: 310,
    id: 52976,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=William%20Morris",
  },
  {
    name: "Charlotte Price",
    totalRecipes: 26,
    totalVideos: 18,
    followers: 13700,
    following: 230,
    id: 52817,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Charlotte%20Price",
  },
  {
    name: "Benjamin Hall",
    totalRecipes: 35,
    totalVideos: 27,
    followers: 18000,
    following: 350,
    id: 52953,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Benjamin%20Hall",
  },
  {
    name: "Amelia Foster",
    totalRecipes: 20,
    totalVideos: 14,
    followers: 10200,
    following: 180,
    id: 52874,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Amelia%20Foster",
  },
  {
    name: "Lucas Cooper",
    totalRecipes: 38,
    totalVideos: 31,
    followers: 19500,
    following: 370,
    id: 52991,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Lucas%20Cooper",
  },
  {
    name: "Harper Kelly",
    totalRecipes: 23,
    totalVideos: 17,
    followers: 12800,
    following: 210,
    id: 52811,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Harper%20Kelly",
  },
  {
    name: "Henry Reed",
    totalRecipes: 30,
    totalVideos: 22,
    followers: 14800,
    following: 290,
    id: 52930,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Henry%20Reed",
  },
  {
    name: "Evelyn Brooks",
    totalRecipes: 27,
    totalVideos: 19,
    followers: 13200,
    following: 240,
    id: 52855,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Evelyn%20Brooks",
  },
  {
    name: "Alexander Gray",
    totalRecipes: 41,
    totalVideos: 33,
    followers: 20200,
    following: 410,
    id: 52908,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Alexander%20Gray",
  },
  {
    name: "Grace Simmons",
    totalRecipes: 19,
    totalVideos: 13,
    followers: 9600,
    following: 170,
    id: 52840,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Grace%20Simmons",
  },
  {
    name: "Daniel Hayes",
    totalRecipes: 34,
    totalVideos: 26,
    followers: 17800,
    following: 330,
    id: 52969,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Daniel%20Hayes",
  },
  {
    name: "Chloe Bennett",
    totalRecipes: 21,
    totalVideos: 15,
    followers: 11000,
    following: 190,
    id: 52802,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Chloe%20Bennett",
  },
  {
    name: "Matthew Ross",
    totalRecipes: 36,
    totalVideos: 28,
    followers: 18300,
    following: 360,
    id: 52944,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Matthew%20Ross",
  },
  {
    name: "Ella Price",
    totalRecipes: 25,
    totalVideos: 18,
    followers: 14100,
    following: 250,
    id: 52868,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Ella%20Price",
  },
  {
    name: "Jackson Cox",
    totalRecipes: 32,
    totalVideos: 24,
    followers: 16500,
    following: 300,
    id: 52921,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Jackson%20Cox",
  },
  {
    name: "Lily Ward",
    totalRecipes: 17,
    totalVideos: 11,
    followers: 8800,
    following: 140,
    id: 52849,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Lily%20Ward",
  },
  {
    name: "Samuel Bennett",
    totalRecipes: 39,
    totalVideos: 30,
    followers: 19000,
    following: 380,
    id: 52935,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Samuel%20Bennett",
  },
  {
    name: "Zoe Foster",
    totalRecipes: 22,
    totalVideos: 16,
    followers: 11600,
    following: 200,
    id: 52825,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Zoe%20Foster",
  },
  {
    name: "Owen Peterson",
    totalRecipes: 30,
    totalVideos: 23,
    followers: 15000,
    following: 290,
    id: 52959,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Owen%20Peterson",
  },
  {
    name: "Hannah Hughes",
    totalRecipes: 24,
    totalVideos: 18,
    followers: 12900,
    following: 220,
    id: 52888,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Hannah%20Hughes",
  },
  {
    name: "Leo Brooks",
    totalRecipes: 28,
    totalVideos: 21,
    followers: 15700,
    following: 275,
    id: 52912,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Leo%20Brooks",
  },
  {
    name: "Avery Russell",
    totalRecipes: 19,
    totalVideos: 14,
    followers: 9400,
    following: 160,
    id: 52859,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Avery%20Russell",
  },
  {
    name: "Caleb Hughes",
    totalRecipes: 33,
    totalVideos: 25,
    followers: 17200,
    following: 320,
    id: 52980,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Caleb%20Hughes",
  },
  {
    name: "Scarlett James",
    totalRecipes: 27,
    totalVideos: 19,
    followers: 13500,
    following: 240,
    id: 52805,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Scarlett%20James",
  },
  {
    name: "Julian Reed",
    totalRecipes: 35,
    totalVideos: 26,
    followers: 17700,
    following: 340,
    id: 52928,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Julian%20Reed",
  },
  {
    name: "Grace Coleman",
    totalRecipes: 21,
    totalVideos: 15,
    followers: 10800,
    following: 190,
    id: 52832,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Grace%20Coleman",
  },
  {
    name: "Wyatt Fisher",
    totalRecipes: 31,
    totalVideos: 24,
    followers: 16200,
    following: 305,
    id: 52966,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Wyatt%20Fisher",
  },
  {
    name: "Luna Hayes",
    totalRecipes: 18,
    totalVideos: 12,
    followers: 8700,
    following: 150,
    id: 52846,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Luna%20Hayes",
  },
  {
    name: "Isaac Powell",
    totalRecipes: 37,
    totalVideos: 29,
    followers: 18500,
    following: 360,
    id: 52950,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Isaac%20Powell",
  },
  {
    name: "Chloe Knight",
    totalRecipes: 23,
    totalVideos: 17,
    followers: 13000,
    following: 230,
    id: 52819,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Chloe%20Knight",
  },
  {
    name: "Sebastian Price",
    totalRecipes: 34,
    totalVideos: 27,
    followers: 17900,
    following: 345,
    id: 52971,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Sebastian%20Price",
  },
  {
    name: "Zara Reed",
    totalRecipes: 26,
    totalVideos: 18,
    followers: 14000,
    following: 255,
    id: 52808,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Zara%20Reed",
  },
  {
    name: "Ryan Brooks",
    totalRecipes: 32,
    totalVideos: 24,
    followers: 16800,
    following: 315,
    id: 52936,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Ryan%20Brooks",
  },
  {
    name: "Nora Ellis",
    totalRecipes: 20,
    totalVideos: 14,
    followers: 9900,
    following: 170,
    id: 52861,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Nora%20Ellis",
  },
  {
    name: "Omar Hughes",
    totalRecipes: 29,
    totalVideos: 22,
    followers: 15100,
    following: 290,
    id: 52958,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Omar%20Hughes",
  },
  {
    name: "Peyton Russell",
    totalRecipes: 24,
    totalVideos: 17,
    followers: 12400,
    following: 225,
    id: 52829,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Peyton%20Russell",
  },
  {
    name: "Calvin Ford",
    totalRecipes: 36,
    totalVideos: 28,
    followers: 18400,
    following: 355,
    id: 52942,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Calvin%20Ford",
  },
  {
    name: "Violet Shaw",
    totalRecipes: 19,
    totalVideos: 13,
    followers: 9700,
    following: 180,
    id: 52844,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Violet%20Shaw",
  },
  {
    name: "Elias Bennett",
    totalRecipes: 33,
    totalVideos: 25,
    followers: 17000,
    following: 325,
    id: 52981,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Elias%20Bennett",
  },
  {
    name: "Ruby Cooper",
    totalRecipes: 22,
    totalVideos: 16,
    followers: 11800,
    following: 205,
    id: 52810,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Ruby%20Cooper",
  },
  {
    name: "Adrian Lee",
    totalRecipes: 38,
    totalVideos: 30,
    followers: 19800,
    following: 390,
    id: 52996,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Adrian%20Lee",
  },
  {
    name: "Madison Hayes",
    totalRecipes: 25,
    totalVideos: 18,
    followers: 14300,
    following: 265,
    id: 52870,
    image: "https://api.dicebear.com/6.x/adventurer/svg?seed=Madison%20Hayes",
  },
];
