name: Update APK Link

on:
  push:
    branches:
      - master

jobs:
  update-apk:
    if: github.actor != 'github-actions'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install -g eas-cli
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Get latest APK link
        id: apk
        run: |
          APK_URL=$(eas build:list --platform android --limit 1 --status finished --json --non-interactive | jq -r '.[0].artifacts.buildUrl')
          if [ -z "$APK_URL" ] || [ "$APK_URL" = "null" ]; then
            echo "No APK URL found!"
            exit 1
          fi
          echo "apk_url=$APK_URL" >> $GITHUB_OUTPUT
        env:
          EXPO_TOKEN: ${{ secrets.EAS_TOKEN }}

      - name: Update README if needed
        run: |
          CURRENT_LINK=$(grep -oP '(?<=APK Download: \[Click Here\]\().*(?=\))' readme.md || echo "")
          if [ "$CURRENT_LINK" != "${{ steps.apk.outputs.apk_url }}" ]; then
            echo "Updating APK link..."
            if grep -q "APK Download:" readme.md; then
              sed -i "s|APK Download: .*|APK Download: [Click Here](${{ steps.apk.outputs.apk_url }})|" readme.md
            else
              echo -e "\nAPK Download: [Click Here](${{ steps.apk.outputs.apk_url }})" >> readme.md
            fi
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add readme.md
            git commit -m "Update APK link [skip ci]"
            git push
          else
            echo "APK link is already up to date, skipping commit."
          fi
